hwi_oauth:
    resource_owners:
        google:
            type:                google
            client_id:           "%env(GOOGLE_CLIENT_ID)%"
            client_secret:       "%env(GOOGLE_CLIENT_SECRET)%"
            scope:               "email profile"

    connect:
        account_connector: App\Security\Google\OAuthConnector
        registration_form: App\Form\RegistrationFormType
        registration_form_handler: App\Security\Google\FormHandler
